//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteGui {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLiteGuiStringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLiteGuiStringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteGui.SQLiteGuiStringResource", typeof(SQLiteGuiStringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the Table ähnelt.
        /// </summary>
        internal static string AddTableWindowNameLbl {
            get {
                return ResourceManager.GetString("AddTableWindowNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Table ähnelt.
        /// </summary>
        internal static string AddTableWindowNameTitel {
            get {
                return ResourceManager.GetString("AddTableWindowNameTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute ähnelt.
        /// </summary>
        internal static string BtnExecute {
            get {
                return ResourceManager.GetString("BtnExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Target Table to as Source to ähnelt.
        /// </summary>
        internal static string InputLblDescriptionCopy {
            get {
                return ResourceManager.GetString("InputLblDescriptionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename selected Table ähnelt.
        /// </summary>
        internal static string InputLblDescriptionRename {
            get {
                return ResourceManager.GetString("InputLblDescriptionRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Primary Key please provide a where clause ähnelt.
        /// </summary>
        internal static string InputLblDescriptionWhereClause {
            get {
                return ResourceManager.GetString("InputLblDescriptionWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source ähnelt.
        /// </summary>
        internal static string InputLblFirstSourceCopy {
            get {
                return ResourceManager.GetString("InputLblFirstSourceCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old Name ähnelt.
        /// </summary>
        internal static string InputLblFirstSourceRename {
            get {
                return ResourceManager.GetString("InputLblFirstSourceRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column ähnelt.
        /// </summary>
        internal static string InputLblFirstWhere {
            get {
                return ResourceManager.GetString("InputLblFirstWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target ähnelt.
        /// </summary>
        internal static string InputLblSecondTargetCopy {
            get {
                return ResourceManager.GetString("InputLblSecondTargetCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Name ähnelt.
        /// </summary>
        internal static string InputLblSecondTargetRename {
            get {
                return ResourceManager.GetString("InputLblSecondTargetRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string InputLblSecondValueWhere {
            get {
                return ResourceManager.GetString("InputLblSecondValueWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Table ähnelt.
        /// </summary>
        internal static string InputWindowTitleCopy {
            get {
                return ResourceManager.GetString("InputWindowTitleCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename Table ähnelt.
        /// </summary>
        internal static string InputWindowTitleRename {
            get {
                return ResourceManager.GetString("InputWindowTitleRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Where Clause ähnelt.
        /// </summary>
        internal static string InputWindowTitleWhere {
            get {
                return ResourceManager.GetString("InputWindowTitleWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logs ähnelt.
        /// </summary>
        internal static string LogsWindowTitle {
            get {
                return ResourceManager.GetString("LogsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string MsgBxError {
            get {
                return ResourceManager.GetString("MsgBxError", resourceCulture);
            }
        }
    }
}
