<Project Sdk="MSTest.Sdk/3.6.4">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
    <RunSettingsFilePath>D:\Users\peter\Source\Repos\CoreLibrary\Imaging.Filter.Tests\bin\Debug\net9.0-windows\fine-code-coverage\coverage-tool-output\Imaging.Filter.Tests-fcc-mscodecoverage-generated.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imaging\Imaging.csproj" />
  </ItemGroup>

</Project>
